### ISSUE TITLE
Fix the pipeline

### ISSUE THREAD

**Issue by schrink** [0x3327/ERFC-3327-publisher#19]
There seems to be a problem with the automated build (with Eslint - it seems it is not installed https://github.com/0x3327/ERFC-3327-publisher/runs/6376712825?check_suite_focus=true
<img width="954" alt="Bump_inquirer_from_7_3_3_to_8_2_4_·_0x3327_ERFC-3327-publisher_2bca9d0" src="https://user-images.githubusercontent.com/2532619/167710805-289fb625-216e-482f-bcfc-008a03896f90.png">

**Comment by AleksWork** [comment]
Fixed Eslint. Works now
